---
- hosts: mywebserver
  become: yes 
  tasks:
    - name: install java on redhat node
      dnf:
        name: "{{myjavapackonredhat}}"
        state: present
      when: ansible_os_family=="RedHat"
