---
- hosts: 172.31.28.251
  become: yes 
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
     dnf: 
      name: httpd
      state: present

  - name: copy test file
    copy:
     src: mytestfile
     dest: /home/maha/mytestfile

    