---
- hosts: 172.31.28.251
  become: yes 
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    dnf: 
     name: httpd
     state: present

  - name: copy text file
    copy:
      src: mytestfile
      dest: /home/maha/mytestfile

  - name: start webserver
    service: 
      name: httpd
      state: started

  - name: download internet file
    get_url: 
     url: https://tomcat.apache.org/download-80.cgi
     dest: /home/maha/download-80.cgi
     force_basic_auth: yes

  - name: copy file into node side
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html

    