---
- hosts: 172.31.28.251
  become: yes 
  tasks:
    - name: install webserver
      include_tasks: myfile.yml

    - name: copy test file
      copy:
        src: mytestfile
        dest: /home/maha/mytestfile


    