---
- hosts: mywebserver
  become: true
  gather_facts: yes
  tasks:
   - name: install web server on RedHat nodes
     dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    
   - name: start webserver on RedHat nodes
     service:
      name: "{{mywebpackonredhat}}"
      state: started
    